version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:9
    container_name: flyway
    depends_on:
      - postgres
    command:
      - -url=jdbc:postgresql://postgres:5432/mydb
      - -user=myuser
      - -password=mypassword
      - -schemas=commerce
      - -createSchemas=true
#      - -baselineOnMigrate=true
      - -locations=filesystem:/flyway/sql
      - migrate

    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA__LISTENERS: PLAINTEXT://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes

      # Set default replication factor here:
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1

      # Optional: for automatic topic creation replication factor
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_INTERNAL://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      # Advertise two listeners:
      # - PLAINTEXT_INTERNAL for internal Docker communication
      # - PLAINTEXT for external clients (your Spring Boot app on localhost)
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      # Listeners Kafka binds to inside container
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29093

      # What Kafka tells clients to connect to:
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_INTERNAL://kafka:29093


    extra_hosts:
      - "localhost:127.0.0.1"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: springboot-app
#    depends_on:
#      - postgres
#      - kafka
#      - redis
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
#      SPRING_DATASOURCE_USERNAME: myuser
#      SPRING_DATASOURCE_PASSWORD: mypassword
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092 ## localhost:29093 maybe?
#      SPRING_REDIS_HOST: redis
#    ports:
#      - "8080:8080"

volumes:
  postgres_data:
